{% extends device_type %}

{% block job_name %}lkft-android-{{KERNEL_BRANCH}}-{{BUILD_NUMBER}}-boot{% endblock job_name %}

{% block job_gobal_timeout %}
timeouts:
  job:
    minutes: 60
  action:
    minutes: 15
  connection:
    minutes: 2
{% endblock job_gobal_timeout %}

{% block test_target %}
- test:
      docker:
        image: yongqinliu/linaro-android-docker:0.1
      timeout:
        minutes: 30
      definitions:
        - repository: https://git.linaro.org/qa/test-definitions.git
          from: git
          path: automated/android/boottime/boottime.yaml
          name: boottime-test

{% endblock test_target %}
