- string:
    name: IMAGES
    default: 'rpb-console-image rpb-console-image-test'
- string:
    name: IMAGES_RPB
    default: 'rpb-desktop-image rpb-desktop-image-test'
- string:
    name: IMAGES_RPB_WAYLAND
    default: 'rpb-weston-image rpb-weston-image-test'
- string:
    name: MANIFEST_URL
    default: 'https://github.com/96boards/oe-rpb-manifest.git'
- string:
    name: MANIFEST_BRANCH
    default: 'sumo'
- string:
    name: BASE_URL
    default: 'http://snapshots.linaro.org/'
- string:
    name: LAVA_SERVER
    default: 'validation.linaro.org/RPC2/'
- string:
    name: QA_SERVER
    default: 'https://qa-reports.linaro.org'
- string:
    name: QA_SERVER_TEAM
    default: 'rpb'
- string:
    name: QA_SERVER_PROJECT
    default: 'rpb-oe'
