- hosts: all
  vars_files:
    ../vars/vars.yml
  tasks:
    - name: create build workspace
      file:
        path: "{{ build_dir }}"
        state: directory

    - name: install pytorch build requirements
      become: yes
      dnf:
        name:
          - cmake
          - gcc-c++
          - make
          - patch
          - python3
          - python3-devel
          - python3-virtualenv
        state: present

    - name: fetch pytorch source
      git:
        repo: "https://github.com/pytorch/pytorch.git"
        dest: "{{ build_dir }}/pytorch/"
        depth: 1
        recursive: yes
        force: yes

    - name: install required Python packages
      pip:
        name:
          - dataclasses
          - pyyaml
          - wheel
        virtualenv: "{{ build_dir }}/virtualenv"

    - name: fetch patch to build pytorch under CentOS 8
      get_url:
        url: "https://github.com/hrw/pytorch/commit/c79701d0696faabdad8dfe12a7ce1d588bbf8469.patch"
        dest: "{{ build_dir }}/c79701d0696faabdad8dfe12a7ce1d588bbf8469.patch"
        mode: 0600

    - name: patch to build under CentOS 8
      patch:
        src: "{{ build_dir }}/c79701d0696faabdad8dfe12a7ce1d588bbf8469.patch"
        basedir: "{{ build_dir }}/pytorch"
        strip: 1

    - name: build pytorch
      shell:
        cmd: |
          set -xe
          source "{{ build_dir }}/virtualenv/bin/activate"
          USE_CUDA=0 BUILD_CAFFE2_OPS=0 USE_DISTRIBUTED=0 USE_QNNPACK=0 USE_XNNPACK=0 python3 setup.py install
          pip wheel .
        chdir: "{{ build_dir }}/pytorch/"
        creates: "{{ build_dir }}/out/build/"

    - name: prepare wheels for publishing
      shell:
        cmd: |
          set -xe
          for pkg in *.whl
          do
            pkgdir=$(echo `basename $pkg`|cut -d'-' -f1 | tr '[:upper:]' '[:lower:]')
            mkdir -p "{{ build_dir }}/out/$pkgdir"
            cp $pkg  "{{ build_dir }}/out/$pkgdir"
          done
        chdir: "{{ build_dir }}/pytorch/"
        creates: "{{ build_dir }}/out/torch/"
