- name: build wheels of binary Python package {{ item }} # noqa 301
  shell:
    cmd: |
      NPY_NUM_BUILD_JOBS=$(nproc) \
      GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS=$(nproc) \
      pip3 wheel -w '{{ wheels_dir }}' \
        --extra-index-url {{ pip_extra_index_url }} \
        "{{ item }}"
    executable: /bin/bash

- name: get name of built wheel file
  find:
    path: "{{ wheels_dir }}"
    patterns: "{{ item | regex_replace('=.*', '') }}*.whl"
    file_type: file
  register: wheel_file

- name: install {{ item }} Python package
  become: yes
  pip:
    name: "{{ wheel_file.files | map(attribute='path') | list }}"
