- hosts: all
  vars_files:
    ../vars/vars.yml
  tasks:
    - name: create build workspace
      tempfile:
        state: directory
      register: build_dir

    - name: include Python tasks
      include_tasks: build_python.yml

    - name: prepare wheels for publishing # noqa 301
      shell:
        cmd: |
          set -xe

          ls -R .

          for pkg in *.whl
          do
            pkgdir=$(echo `basename $pkg`|cut -d'-' -f1 | tr '[:upper:]_' '[:lower:]-')
            mkdir -p "{{ wheels_dir }}/$pkgdir"
            mv $pkg  "{{ wheels_dir }}/$pkgdir"

            # do we have this package in cache already?
            status=$(curl --head --silent {{ pip_extra_index_url }}/${pkgdir}/${pkg} | head -n 1)
            if $(echo $status | grep -q 404); then
              echo "uploading $pkgdir/$pkg"
            else
              rm -rf "{{ wheels_dir }}/$pkgdir/$pkg"
            fi
          done

        chdir: "{{ wheels_dir }}"
        executable: "/bin/bash"

    - name: remove build workspace
      file:
        path: "{{ build_dir.path }}"
        state: absent
      when: build_dir.path is defined
